import html2canvas from "html2canvas-pro";
import { jsPDF } from "jspdf";

/**
 * Render a DOM node into a multi-page A4 PDF and trigger download.
 * Uses html2canvas-pro to support modern CSS color functions (oklch, color-mix)
 * generated by Tailwind v4, then slices the canvas across A4 pages.
 */
export async function downloadNodeAsPdf(
  node: HTMLElement,
  fileName: string,
): Promise<void> {
  // High-DPI capture for crisp text in the PDF.
  const canvas = await html2canvas(node, {
    scale: 2,
    useCORS: true,
    backgroundColor: "#ffffff",
    logging: false,
    windowWidth: node.scrollWidth,
    windowHeight: node.scrollHeight,
  });

  const imgData = canvas.toDataURL("image/jpeg", 0.95);

  // A4 in millimetres.
  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });
  const pageWidth = pdf.internal.pageSize.getWidth(); // 210
  const pageHeight = pdf.internal.pageSize.getHeight(); // 297

  // Convert canvas pixels into mm at the page width.
  const imgWidth = pageWidth;
  const imgHeight = (canvas.height * imgWidth) / canvas.width;

  let heightLeft = imgHeight;
  let position = 0;

  pdf.addImage(imgData, "JPEG", 0, position, imgWidth, imgHeight);
  heightLeft -= pageHeight;

  while (heightLeft > 0) {
    position = heightLeft - imgHeight;
    pdf.addPage();
    pdf.addImage(imgData, "JPEG", 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;
  }

  const safeName = fileName.replace(/[\\/:*?"<>|]/g, "_").trim() || "CV";
  pdf.save(`${safeName}.pdf`);
}
